### ISSUE TITLE
Server crashes randomly - 1.20.1

### ISSUE THREAD

**Issue by Mekrip** [FatherToast/SpecialMobs#40]
Hey,
unfortunately I have the problem that my Minecraft server crashes randomly with the mod.
I don't know why this happens. Before the crash I was running around in the world.

Crash report:
[crash-2024-07-12_19.13.22-server.txt](https://github.com/user-attachments/files/16199066/crash-2024-07-12_19.13.22-server.txt)

Modlist:
[modlist.html.txt](https://github.com/user-attachments/files/16199071/modlist.html.txt)

After removing the mod, everything seems to be fine.

Best regards

**Comment by Sarinsa** [comment]
Okay so I am going to take a shot in the dark here and say that this is very likely a worldgen deadlock that happens because we did some unsafe things with mob replacement. Luckily we have investigated this now and believe we have a fix ready for the coming update. If you still get the same type of crash after the new version has been released, re-open this issue and I'll take a look
